version: "3.8"

services:
  ocular:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OCULAR_GENESIS_HOST: /api
    image: ocular:local
    environment:
      OCULAR_DEMO: "false"
    restart: unless-stopped

  genesis:
    image: ghcr.io/simonwep/genesis:latest
    env_file: .env.genesis
    volumes:
      - ./data:/app/.data
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3030:80"
    depends_on:
      - ocular
      - genesis
    restart: unless-stopped
